tagline: where service meets luxury
email: olajumokeh.osadola@hannahshandseventsco.com
instagram: hannahs_handsevents
facebook: hannahshandseventcompany
calendlyUrl: >-
  https://calendly.com/olajumokeh-osadola-hannahshandseventsco/discovery-consultation
stats:
  - number: 8+
    label: Years Experience
  - number: '7'
    label: Signature Services
  - number: '2018'
    label: Flagship Since
  - number: 100%
    label: Bespoke
